### ISSUE TITLE
Cura 4.0 support?

### ISSUE THREAD

**Issue by Fixx** [MoonCactus/gcode_postprocessors#6]
Since Cura introduced latest 4.0 version with improved plugin support, I think it's time to fix wood script for Cura 4.0.

**Comment by MoonCactus** [comment]
Sorry guys
Cura is now 4.2, but I had once again to reset all my profiles due to their amazingly consistent self-incompatibilities... E.g. https://github.com/Ultimaker/Cura/issues/5581#issuecomment-516943798 
So I will still wait a bit... Amazing :/
